{
    "name": """QR Code Scanning in POS""",
    "summary": """Scans QR codes via device's camera""",
    "category": "Point of Sale",
    # "live_test_url": "",
    "images": ["images/main.png"],
    "version": "19.0.1.0.0",
    "application": False,
    "author": "IT-Projects LLC",
    "support": "apps@it-projects.info",
    "website": "https://it-projects.info",
    "license": "Other OSI approved licence",  # MIT
    # "price": 20.00,
    # "currency": "EUR",
    "depends": ["itp_pos_qr_payments", "point_of_sale"],
    "external_dependencies": {"python": [], "bin": []},
    "data": [],
    "assets": {
        "point_of_sale.assets_prod": [
            "itp_pos_qr_scan/static/src/css/pos.css",
            "itp_pos_qr_scan/static/lib/jsqrcode/grid.js",
            "itp_pos_qr_scan/static/lib/jsqrcode/version.js",
            "itp_pos_qr_scan/static/lib/jsqrcode/detector.js",
            "itp_pos_qr_scan/static/lib/jsqrcode/formatinf.js",
            "itp_pos_qr_scan/static/lib/jsqrcode/errorlevel.js",
            "itp_pos_qr_scan/static/lib/jsqrcode/bitmat.js",
            "itp_pos_qr_scan/static/lib/jsqrcode/datablock.js",
            "itp_pos_qr_scan/static/lib/jsqrcode/bmparser.js",
            "itp_pos_qr_scan/static/lib/jsqrcode/datamask.js",
            "itp_pos_qr_scan/static/lib/jsqrcode/rsdecoder.js",
            "itp_pos_qr_scan/static/lib/jsqrcode/gf256poly.js",
            "itp_pos_qr_scan/static/lib/jsqrcode/gf256.js",
            "itp_pos_qr_scan/static/lib/jsqrcode/decoder.js",
            "itp_pos_qr_scan/static/lib/jsqrcode/qrcode.js",
            "itp_pos_qr_scan/static/lib/jsqrcode/findpat.js",
            "itp_pos_qr_scan/static/lib/jsqrcode/alignpat.js",
            "itp_pos_qr_scan/static/lib/jsqrcode/databr.js",
            "itp_pos_qr_scan/static/src/js/qr_scan.js",
            "itp_pos_qr_scan/static/src/js/Popups/QRScanPopup.js",
            "itp_pos_qr_scan/static/src/js/Screens/ProductScreen/ControlButtons/QRButton.js",
            "itp_pos_qr_scan/static/src/xml/Popups/QRScanPopup.xml",
            "itp_pos_qr_scan/static/src/xml/Screens/ProductScreen/ControlButtons/QRButton.xml",

        ],
        "point_of_sale.assets": [
            "itp_pos_qr_scan/static/src/css/pos.css",
            "itp_pos_qr_scan/static/lib/jsqrcode/grid.js",
            "itp_pos_qr_scan/static/lib/jsqrcode/version.js",
            "itp_pos_qr_scan/static/lib/jsqrcode/detector.js",
            "itp_pos_qr_scan/static/lib/jsqrcode/formatinf.js",
            "itp_pos_qr_scan/static/lib/jsqrcode/errorlevel.js",
            "itp_pos_qr_scan/static/lib/jsqrcode/bitmat.js",
            "itp_pos_qr_scan/static/lib/jsqrcode/datablock.js",
            "itp_pos_qr_scan/static/lib/jsqrcode/bmparser.js",
            "itp_pos_qr_scan/static/lib/jsqrcode/datamask.js",
            "itp_pos_qr_scan/static/lib/jsqrcode/rsdecoder.js",
            "itp_pos_qr_scan/static/lib/jsqrcode/gf256poly.js",
            "itp_pos_qr_scan/static/lib/jsqrcode/gf256.js",
            "itp_pos_qr_scan/static/lib/jsqrcode/decoder.js",
            "itp_pos_qr_scan/static/lib/jsqrcode/qrcode.js",
            "itp_pos_qr_scan/static/lib/jsqrcode/findpat.js",
            "itp_pos_qr_scan/static/lib/jsqrcode/alignpat.js",
            "itp_pos_qr_scan/static/lib/jsqrcode/databr.js",
            "itp_pos_qr_scan/static/src/js/qr_scan.js",
            "itp_pos_qr_scan/static/src/js/Popups/QRScanPopup.js",
            "itp_pos_qr_scan/static/src/js/Screens/ProductScreen/ControlButtons/QRButton.js",
            "itp_pos_qr_scan/static/src/xml/Popups/QRScanPopup.xml",
            "itp_pos_qr_scan/static/src/xml/Screens/ProductScreen/ControlButtons/QRButton.xml",

        ],
        "point_of_sale.assets_pos": [
            "itp_pos_qr_scan/static/src/css/pos.css",
            "itp_pos_qr_scan/static/lib/jsqrcode/grid.js",
            "itp_pos_qr_scan/static/lib/jsqrcode/version.js",
            "itp_pos_qr_scan/static/lib/jsqrcode/detector.js",
            "itp_pos_qr_scan/static/lib/jsqrcode/formatinf.js",
            "itp_pos_qr_scan/static/lib/jsqrcode/errorlevel.js",
            "itp_pos_qr_scan/static/lib/jsqrcode/bitmat.js",
            "itp_pos_qr_scan/static/lib/jsqrcode/datablock.js",
            "itp_pos_qr_scan/static/lib/jsqrcode/bmparser.js",
            "itp_pos_qr_scan/static/lib/jsqrcode/datamask.js",
            "itp_pos_qr_scan/static/lib/jsqrcode/rsdecoder.js",
            "itp_pos_qr_scan/static/lib/jsqrcode/gf256poly.js",
            "itp_pos_qr_scan/static/lib/jsqrcode/gf256.js",
            "itp_pos_qr_scan/static/lib/jsqrcode/decoder.js",
            "itp_pos_qr_scan/static/lib/jsqrcode/qrcode.js",
            "itp_pos_qr_scan/static/lib/jsqrcode/findpat.js",
            "itp_pos_qr_scan/static/lib/jsqrcode/alignpat.js",
            "itp_pos_qr_scan/static/lib/jsqrcode/databr.js",
            "itp_pos_qr_scan/static/src/js/qr_scan.js",
            "itp_pos_qr_scan/static/src/js/Popups/QRScanPopup.js",
            "itp_pos_qr_scan/static/src/js/Screens/ProductScreen/ControlButtons/QRButton.js",
            "itp_pos_qr_scan/static/src/xml/Popups/QRScanPopup.xml",
            "itp_pos_qr_scan/static/src/xml/Screens/ProductScreen/ControlButtons/QRButton.xml",

        ],
        "point_of_sale._assets_pos": [
            "itp_pos_qr_scan/static/src/css/pos.css",
            "itp_pos_qr_scan/static/lib/jsqrcode/grid.js",
            "itp_pos_qr_scan/static/lib/jsqrcode/version.js",
            "itp_pos_qr_scan/static/lib/jsqrcode/detector.js",
            "itp_pos_qr_scan/static/lib/jsqrcode/formatinf.js",
            "itp_pos_qr_scan/static/lib/jsqrcode/errorlevel.js",
            "itp_pos_qr_scan/static/lib/jsqrcode/bitmat.js",
            "itp_pos_qr_scan/static/lib/jsqrcode/datablock.js",
            "itp_pos_qr_scan/static/lib/jsqrcode/bmparser.js",
            "itp_pos_qr_scan/static/lib/jsqrcode/datamask.js",
            "itp_pos_qr_scan/static/lib/jsqrcode/rsdecoder.js",
            "itp_pos_qr_scan/static/lib/jsqrcode/gf256poly.js",
            "itp_pos_qr_scan/static/lib/jsqrcode/gf256.js",
            "itp_pos_qr_scan/static/lib/jsqrcode/decoder.js",
            "itp_pos_qr_scan/static/lib/jsqrcode/qrcode.js",
            "itp_pos_qr_scan/static/lib/jsqrcode/findpat.js",
            "itp_pos_qr_scan/static/lib/jsqrcode/alignpat.js",
            "itp_pos_qr_scan/static/lib/jsqrcode/databr.js",
            "itp_pos_qr_scan/static/src/js/qr_scan.js",
            "itp_pos_qr_scan/static/src/js/Popups/QRScanPopup.js",
            "itp_pos_qr_scan/static/src/js/Screens/ProductScreen/ControlButtons/QRButton.js",
            "itp_pos_qr_scan/static/src/xml/Popups/QRScanPopup.xml",
            "itp_pos_qr_scan/static/src/xml/Screens/ProductScreen/ControlButtons/QRButton.xml",

        ],
    },


    "auto_install": False,
    "installable": True,
}

